Generate encrypted PKCS1 test certs
Change-Id: I1603f0199d9551bb89283156e7a7a031996ffa45
Reviewed-on: http://review.couchbase.org/c/ns_server/+/160242
Well-Formed: Build Bot <build@couchbase.com>
Reviewed-by: Artem Stemkovski <artem@couchbase.com>
Tested-by: Timofey Barmin <timofey.barmin@couchbase.com>

diff --git a/scripts/certs_generation/generate_node_cert b/scripts/certs_generation/generate_node_cert
--- a/scripts/certs_generation/generate_node_cert
+++ b/scripts/certs_generation/generate_node_cert
@@ -49,7 +49,17 @@ intermediate_dir_abs=$(abs_path "${intermediate_dir}")
 echo "Creating a key..."
 mkdir "${out_node_dir}/private"
 keyfile="${out_node_dir}/private/${hostname}.key.pem"
-openssl genrsa  -out "${keyfile}" 2048
+read -e -p "Should the node private key be encrypted? y/[n]: " pkey_encrypted
+if [[ "$pkey_encrypted" == "y" ]]; then
+    echo "Enter passphrase: "
+    openssl genrsa -aes256 -passout stdin  -out "${keyfile}" 2048
+elif [[ "$pkey_encrypted" == "n" ]]; then
+    openssl genrsa  -out "${keyfile}" 2048
+else
+    echo "invalid reply: $pkey_encrypted"
+    exit 1
+fi
+
 chmod 400 "${keyfile}"
 
 echo "Creating a certificate signing request..."
