Fix typos in scripts/review
Change-Id: I8ef3f3d155d3c722e55f4c0c90ff503f5d76787c
Reviewed-on: http://review.couchbase.org/92265
Tested-by: Timofey Barmin <timofey.barmin@couchbase.com>
Well-Formed: Build Bot <build@couchbase.com>
Reviewed-by: Aliaksey Artamonau <aliaksey.artamonau@couchbase.com>

diff --git a/scripts/review b/scripts/review
--- a/scripts/review
+++ b/scripts/review
@@ -164,7 +164,7 @@ if [ "${SUBMIT}" = yes ]; then
 fi
 
 if [ -z "${FLAGS}" -a -z "$RAW" ]; then
-    usage "Need at least on of --verified, --review, --submit or --raw"
+    usage "Need at least one of --verified, --review, --submit or --raw"
 fi
 
 if [ -z "${BRANCH}" ]; then
@@ -178,7 +178,7 @@ if [ -z "${UPSTREAM}" ]; then
 fi
 
 REVIEW_URL=$(get_review_url) || fail "Failed to get the review URL"
-USERNAME=$(get_review_username "${REVIEW_URL}") || fail "Failed to the username"
+USERNAME=$(get_review_username "${REVIEW_URL}") || fail "Failed to get the username"
 
 if [ -n "${RAW}" ]; then
     if [ -n "${FLAGS}" ]; then
